### ISSUE TITLE
MDP Port Set Exception

### ISSUE THREAD

**Issue by gardners** [servalproject/serval_chat#16]
Reported by a user:

The following Exception occurred in Serval Chat 0.01-pre-162-g692d0de4 and was not caught

MDP port was not set
java.lang.IllegalStateException: MDP port was not set
at org.servalproject.mid.Server.started(Server.java:148)
at org.servalproject.servaldna.ServalDCommand.server(Native Method)
at org.servalproject.mid.Server.run(Server.java:176)
at java.lang.Thread.run(Thread.java:764)

**Comment by lakeman** [comment]
It's going to be difficult to diagnose without any logging. Since new installs seem to work cleanly, was this phone upgraded from a previous version?
