### ISSUE TITLE
NDK Compile Error

### ISSUE THREAD

**Issue by chuncheng1010** [servalproject/serval_chat#9]

**Comment by lakeman** [comment]
So the gradle task  libsodiumx86 didn't run properly? Or output to a
different location?

**Comment by chuncheng1010** [comment]
Thanks for your reply.
I didn't know to compile libsodium first using dist_build.
Currently I resolved the problem.
I have a other problem.
Currently I am implementing voice talk using bluetooth mesh network based on batphone.
For bluetooth mesh network I made it.
This is my code.

server = ServalD.getServer(null, this);
server.start();
But serer.start() crashes.
This is logcat

07-11 22:14:15.185 3981-4035/com.example.lcs.bluetoothmeshchat E/AndroidRuntime: FATAL EXCEPTION: Servald
    Process: com.example.lcs.bluetoothmeshchat, PID: 3981
    java.lang.IllegalStateException: Failed to bind sockets
        at org.servalproject.servaldna.ServalDCommand.server(Native Method)
        at org.servalproject.servald.ServalD$4.run(ServalD.java:368)
        at java.lang.Thread.run(Thread.java:776)

ServalDCommand.server(ServalD.this, "", null);
I think there is a problem in there.
But this method calls native method server(IJniServer callback, String keyringPin, String[] entryPins)
So Now I can not know reason.
Looking forward to your reply
Thanks
